// export default Prices{
//     "Corned Beef and Cabbage", 280,
//         "Cevapi Sausages", 300,
//         "Croatian lamb peka", 290,
//         "Croatian Bean Stew", 280,
//         "Chivito uruguayo", 270,
//         "Corned Beef Hash", 285,
//         "Chicken Enchilada Casserole", 280,
//         "Chicken Handi", 380,
//         "Chicken Alfredo Primavera", 285,
//         "Chicken Fajita Mac and Cheese", 260,
//         "Crock Pot Chicken Baked Tacos", 220,
//         "Chicken Karaage", 180,
//         "Coq au vin", 285,
//         "Chicken & mushroom Hotpot", 280,
//         "Chicken Couscous", 170,
//         "Chicken Ham and Leek Pie", 190,
//         "Chicken Parmentier", 240,
//         "Chicken Marengo", 230,
//         "Chicken Basquaise", 290,
//         "Chicken Congee", 300,
//         "Chicken Quinoa Greek Salad", 340,
//         "Chick-Fil-A Sandwich", 270,
//         "Chocolate Gateau", 260,
//         "Christmas Pudding Flapjack", 220,
//         "Chocolate Avocado Mousse", 210,
//         "Choc Chip Pecan Pie", 200,
//         "Chocolate Raspberry Brownies", 280,
//         "Carrot Cake", 290,
//         "Chelsea Buns", 270,
//         "Chocolate Souffle", 380,
//         "Chinon Apple Tarts", 300,
//         "Canadian Butter Tarts", 200,
//         "Chocolate Caramel Crispy", 150,
//         "Cashew Ghoriba Biscuits", 180,
//         "Classic Christmas pudding", 275,
//         "Christmas Pudding Trifle", 255,
//         "Christmas cake", 310,
//         "Callaloo Jamaican Style", 300,
//         "Chakchouka", 280,
//         "Chilli prawn linguine", 285,
//         "Crispy Sausages and Greens", 240,
//         "Coddled pork with cider", 220,
//         "Cajun spiced fish tacos", 200,
//         "Corba", 290,
//         "Cream Cheese Tart", 340,
//         "Clam chowder", 320,
//         "Creamy Tomato Soup", 190,
//         "Chickpea Fajitas", 210,
//         "Crispy Eggplant", 280,
//         "Cabbage Soup (Shchi)", 230

// }
